#!/usr/bin/env bash
#
# Make the in-process loopback engine reachable from the Android WebView
# in RELEASE builds.
#
# Why this is needed: the mobile build links ps5upload-engine in-process
# and binds it to http://127.0.0.1:19113; the renderer fetches that URL
# exactly as on desktop (see engine_mobile.rs + client/src/api/engine.ts).
# Tauri sets `android:usesCleartextTraffic` to TRUE for debug builds but
# FALSE for release, so a release APK silently blocks the renderer's
# cleartext request to loopback and the UI shows the engine as "red".
#
# Fix: add a network-security-config that permits cleartext ONLY for
# 127.0.0.1 / localhost, leaving every other host cleartext-forbidden.
# A networkSecurityConfig reference takes precedence over the
# usesCleartextTraffic flag, so this works for debug and release alike
# without weakening security for real network traffic.
#
# `gen/android` is gitignored and regenerated by `tauri android init`,
# so this MUST run AFTER init and BEFORE `tauri android build`. It is
# idempotent. Invoked from publish.yml, engine-ci.yml, and the Makefile.

set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
gen="$root/client/src-tauri/gen/android/app/src/main"
manifest="$gen/AndroidManifest.xml"
xmldir="$gen/res/xml"

if [ ! -f "$manifest" ]; then
  echo "::error::AndroidManifest.xml not found at $manifest — run 'tauri android init' first" >&2
  exit 1
fi

mkdir -p "$xmldir"
cat >"$xmldir/network_security_config.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Loopback-only cleartext: the in-process ps5upload-engine binds
     127.0.0.1:19113 and the WebView fetches it over plain HTTP. All
     other traffic stays cleartext-forbidden. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
XML
echo "wrote $xmldir/network_security_config.xml"

# Reference the config from <application>, idempotently.
python3 - "$manifest" <<'PY'
import re, sys
path = sys.argv[1]
src = open(path, encoding="utf-8").read()
if "networkSecurityConfig" in src:
    print("manifest already references networkSecurityConfig — skipping")
else:
    new = re.sub(
        r"(<application\b)",
        r'\1 android:networkSecurityConfig="@xml/network_security_config"',
        src,
        count=1,
    )
    if new == src:
        sys.exit("::error::could not find <application> tag to patch")
    open(path, "w", encoding="utf-8").write(new)
    print("patched <application> with networkSecurityConfig")
PY

echo "android loopback-cleartext fix applied"
